name: Build and Upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: clippy (ubuntu-latest, stable)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy

    - name: Restore cargo cache
      uses: actions/cache@v2.1.7
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-stable-${{ hashFiles('Cargo.lock') }}

    - name: Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --no-deps

  check:
    name: check (ubuntu-latest, stable)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Restore cargo cache
      uses: actions/cache@v2.1.7
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-stable-${{ hashFiles('Cargo.lock') }}

    - name: Check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --release

  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust:
          - stable

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
        

      - name: Restore cargo cache
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('Cargo.lock') }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      
      - if: matrix.os == 'ubuntu-latest'
        name: Install Android/arm64 target
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: aarch64-linux-android
          toolchain: stable
                  
      - if: matrix.os == 'ubuntu-latest'
        name: Build Android (arm64)
        uses: actions-rs/cargo@v1
        env:
          TARGET_AR: /usr/local/lib/android/sdk/ndk/24.0.8215888/arm64/bin/aarch64-linux-android-ar
          TARGET_CC: /usr/local/lib/android/sdk/ndk/24.0.8215888/arm64/bin/aarch64-linux-android-clang
        with:
          command: build
          args: --release --target=aarch64-linux-android
        
      - if: matrix.os != 'windows-latest'
        name: Strip
        run: strip target/release/dexios

      - if: matrix.os == 'ubuntu-latest'
        name: Hash the Binary
        run: sha256sum target/release/dexios

      - if: matrix.os == 'ubuntu-latest'
        name: Upload Binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dexios-linux-amd64
          path: target/release/dexios
      - if: matrix.os == 'ubuntu-latest'
        name: Upload Binary as artifact (Android/arm64)
        uses: actions/upload-artifact@v3
        with:
          name: dexios-android-arm64
          path: target/aarch64-linux-android/release/dexios
      - if: matrix.os == 'macos-latest'
        name: Upload Binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dexios-macos-amd64
          path: target/release/dexios
      - if: matrix.os == 'windows-latest'
        name: Upload Binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dexios-windows-amd64
          path: target/release/dexios.exe
